### ISSUE TITLE
Build out a landing page

### ISSUE THREAD

**Issue by premdav** [casamed/BudgetBuddy#4]
We need a landing page to be built that tells the user a little bit about the application and then has links to redirect the user to the login and registration pages.

**Comment by premdav** [comment]
![landingpage](https://user-images.githubusercontent.com/35507470/66719464-c024a000-edb5-11e9-8655-3db49b91835a.jpg)

**Comment by premdav** [comment]
I think these colors would be a good starting point as well.

https://coolors.co/1d1e18-6b8f71-aad2ba-d9fff5-b9f5d8

**Comment by casamed** [comment]
What about these

https://coolors.co/a4bfeb-a3a3a3-6f2dbd-f8e9e9-214f4b
